docker-build:
	docker build -t blaze5333/go-chat-backend:latest .
docker-run:
	docker run -p 8080:8080 blaze5333/go-chat-backend:latest
docker-push:
	docker push blaze5333/go-chat-backend:latest
docker-compose-build:
	docker-compose build
docker-push:
	docker push blaze5333/go-chat-backend:latest
run:
	docker-compose up --build
stop:
	docker-compose down
